### ISSUE TITLE
SyntaxError: Invalid or unexpected token when used in a repeater field

### ISSUE THREAD

**Issue by haggaiwambua** [AbanoubNassem/filament-phone-field#7]
The validation for phone numbers doesn't work when used in a repeater field. The syntax error `Invalid or unexpected token` is logged in the console. Please advice. Thanks

**Comment by AbanoubNassem** [comment]
fixed in  version 0.0.4

**Comment by haggaiwambua** [comment]
Thank you @AbanoubNassem
